from cmath import log
from distutils.sysconfig import PREFIX
import discord
import random
from dotenv import load_dotenv
from discord.ext import commands
import os
load_dotenv()

PREFIX = os.environ['PREFIX']
TOKEN = os.environ['TOKEN']

client = discord.Client()
token = "MTA2NTE4MzQ4MDQyMzY0NTIwNQ.GAghPS.rplKGGm61cgyj-kOCtRuF2cjALHjY5WGlnhJjM"
a = ["누구세요 ?😗","안녕하세요😊","안녕 !😆","반가워 !😚","안녕 ? 나는 포도봇이야 !🍇","너는.. 누구야..?🤔","뿡뿡뿡~💨","야1미~😋","야 뭘봐 !😡","🤔"]

@client.event
async def on_ready():
    print("ready to 포도봇 !")

@client.slash_command(guild_ids = [934742265828614165], description="포도봇에게 인사를 해보세요 !")
async def 인사(ctx):
    rd = random.choice(a)
    embed=discord.Embed(title=" ", color=0xb750fb)
    embed.add_field(name="포도봇 : {}님 {}".format(user.name,rd), value="", inline=True)
    embed.set_footer(text="Made by WELCIKS")
    await ctx.send(embed=embed)

@client.slash_command(guild_ids = [934742265828614165], description="히스터 대머리 ?")
async def 히스터(ctx):
    embed=discord.Embed(title=" ", description="히스터는 대머리다 ?", color=0xb750fb)
    embed.set_author(name="히스터 / Hister")
    embed.add_field(name="", value="", inline=True)
    embed.add_field(name="", value="총 성장시간 : 성장불가", inline=False)
    embed.add_field(name="", value="", inline=True)
    embed.add_field(name="  히스터는 탈모 ? 대머리 ? / 돌도끼한테 케이징 당함", value="", inline=False)
    embed.add_field(name="", value="", inline=True)
    embed.set_footer(text="Made by WELCIKS")
    await ctx.respond(embed=embed)

@client.slash_command(guild_ids = [934742265828614165], description="피피 PiPi")
async def 피피(ctx):
    embed=discord.Embed(title=" ", description="피피 = PiPi = 삐삐", color=0xb750fb)
    embed.set_author(name="피피 / PiPi")
    embed.set_thumbnail(url='https://cdn.discordapp.com/avatars/399048531366772736/824e229fcffb0c9a536e45d90bd69665.webp?size=24')
    embed.add_field(name="", value="", inline=True)
    embed.add_field(name="", value="총 성장시간 : 성장불가", inline=False)
    embed.add_field(name="", value="", inline=True)
    embed.add_field(name="  피피 is 삐삐", value="", inline=False)
    embed.add_field(name="", value="", inline=True)
    embed.set_footer(text="Made by WELCIKS")
    await ctx.respond(embed=embed)

@client.slash_command(guild_ids = [934742265828614165], description="요요 = YOYO")
async def 요요(ctx):
    embed=discord.Embed(title=" ", description="요요 : 루카쿠를 굉장히 사랑함 / 요요", color=0xb750fb)
    embed.set_author(name="요요 / YOYO")
    embed.set_thumbnail(url='https://emojigraph.org/media/google/yo-yo_1fa80.png')
    embed.add_field(name="", value="", inline=True)
    embed.add_field(name="", value="총 성장시간 : 성장불가", inline=False)
    embed.add_field(name="", value="", inline=True)
    embed.add_field(name="  요요 = YOYO = 루카쿠", value="", inline=False)
    embed.add_field(name="", value="", inline=True)
    embed.set_footer(text="Made by WELCIKS")
    await ctx.respond(embed=embed)

@client.slash_command(guild_ids = [934742265828614165], description="디아일 = 크리스탈아일")
async def 아일(ctx):
    embed=discord.Embed(title=" ", description="디아일 / 크아일", color=0xb750fb)
    embed.set_author(name="크리스탈 아일 / Crystal Isles")
    embed.set_thumbnail(url='https://ark.wiki.gg/images/e/e2/The_Island_Map.jpg')
    embed.add_field(name="", value="", inline=True)
    embed.add_field(name="", value="총 성장시간 : 성장불가", inline=False)
    embed.add_field(name="", value="", inline=True)
    embed.add_field(name="  디아일 = 크아일", value="", inline=False)
    embed.add_field(name="", value="", inline=True)
    embed.set_footer(text="Made by WELCIKS")
    await ctx.respond(embed=embed)

@client.slash_command(guild_ids = [934742265828614165], description="기가노토사우루스 성장시간")
async def 기가(ctx):
    embed=discord.Embed(title=" ", description="공식 오피셜 성장시간 ( x 1 )", color=0xb750fb)
    embed.set_author(name="기가노토사우루스 / Giganotosaurus")
    embed.set_thumbnail(url='https://w.namu.la/s/503de9b9720163ed2c4ac240f8e1198c7b756436af83c1680f17d6b770f9dcf65e20df49ad223b5e60bee0e1df972d15c10c2255115518ca2875a2c0c009c2c56b058516e62769c337fcdf907e99decaedc50683fed022dfe576c0756170698f791bc0b1cfe90273feb278bd5cc6aff4')
    embed.add_field(name="", value="", inline=True)
    embed.add_field(name="  성장시간", value="", inline=False)
    embed.add_field(name="", value="총 성장시간 : 10일 3시간 59분", inline=False)
    embed.add_field(name=" ", value="", inline=False)
    embed.add_field(name=" ", value="알 부화시간 : 2일 1시간 59분 45초", inline=False)
    embed.add_field(name=" ", value="베이비 : 1일 23분 54초", inline=False)
    embed.add_field(name=" ", value="성장기 : 4일 1시간 35분 39초", inline=False)
    embed.add_field(name=" ", value="성숙기 : 5일 1시간 59분 34초 ", inline=False)
    embed.add_field(name=" ", value="", inline=False)
    embed.set_footer(text="Made by WELCIKS")
    await ctx.respond(embed=embed)

@client.slash_command(guild_ids = [934742265828614165], description="벨로나사우루스 성장시간")
async def 벨로(ctx):
    embed=discord.Embed(title=" ", description="공식 오피셜 성장시간 ( x 1 )", color=0xb750fb)
    embed.set_author(name="벨로나사우루스 / Velonasaur")
    embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/806894932836220928/806896756998537276/velonasaur.png')
    embed.add_field(name="", value="", inline=True)
    embed.add_field(name="  성장시간", value="", inline=False)
    embed.add_field(name="", value="총 성장시간 : 1일 22시간 17분 46초", inline=False)
    embed.add_field(name=" ", value="", inline=False)
    embed.add_field(name=" ", value="알 부화시간 : 1시간 8분 10초", inline=False)
    embed.add_field(name=" ", value="베이비 : 4시간 37분 46초", inline=False)
    embed.add_field(name=" ", value="성장기 : 18시간 31분 6초", inline=False)
    embed.add_field(name=" ", value="성숙기 : 23시간 8분 53초 ", inline=False)
    embed.add_field(name=" ", value="", inline=False)
    embed.set_footer(text="Made by WELCIKS")
    await ctx.respond(embed=embed)

@client.slash_command(guild_ids = [934742265828614165], description="스테고사우루스 성장시간")
async def 스테고(ctx):
    embed=discord.Embed(title=" ", description="공식 오피셜 성장시간 ( x 1 )", color=0xb750fb)
    embed.set_author(name="스테고사우루스 / Stegosaurus")
    embed.set_thumbnail(url='https://obj-sg.the1.wiki/data/737465676f7361757275732e706e67.png')
    embed.add_field(name="", value="", inline=True)
    embed.add_field(name="  성장시간", value="", inline=False)
    embed.add_field(name="", value="총 성장시간 : 2일 3시간 26분 25초", inline=False)
    embed.add_field(name=" ", value="", inline=False)
    embed.add_field(name=" ", value="알 부화시간 : 2시간 46분 39초", inline=False)
    embed.add_field(name=" ", value="베이비 : 5시간 8분 38초", inline=False)
    embed.add_field(name=" ", value="성장기 : 20시간 34분 34초", inline=False)
    embed.add_field(name=" ", value="성숙기 : 1일 1시간 43분 12초 ", inline=False)
    embed.add_field(name="", value="", inline=True)
    embed.set_footer(text="Made by WELCIKS")
    await ctx.respond(embed=embed)

@client.slash_command(guild_ids = [934742265828614165], description="와이번 성장시간")
async def 와이번(ctx):
    embed=discord.Embed(title=" ", description="공식 오피셜 성장시간 ( x 1 )", color=0xb750fb)
    embed.set_author(name="모든 와이번 / ALL Wyvern")
    embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/806893887162548244/806894009670434856/crystalwyvern.png')
    embed.add_field(name="", value="", inline=True)
    embed.add_field(name="  성장시간", value="", inline=False)
    embed.add_field(name="", value="총 성장시간 : 3일 20시간 35분 33초", inline=False)
    embed.add_field(name=" ", value="", inline=False)
    embed.add_field(name=" ", value="알 부화시간 : 4시간 59분 58초", inline=False)
    embed.add_field(name=" ", value="베이비 : 9시간 15분 33초", inline=False)
    embed.add_field(name=" ", value="성장기 : 1일 13시간 2분 13초", inline=False)
    embed.add_field(name=" ", value="성숙기 : 1일 22시간 17분 46초", inline=False)
    embed.add_field(name="", value="", inline=True)
    embed.set_footer(text="Made by WELCIKS")
    await ctx.respond(embed=embed)

@client.slash_command(guild_ids = [934742265828614165], description="마나가르마 성장시간")
async def 마나(ctx):
    embed=discord.Embed(title=" ", description="공식 오피셜 성장시간 ( x 1 )", color=0xb750fb)
    embed.set_author(name="마나가르마 / Managarmr")
    embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/806894932836220928/806897005195952149/managarmr.png')
    embed.add_field(name="", value="", inline=True)
    embed.add_field(name="  성장시간", value="", inline=False)
    embed.add_field(name="", value="총 성장시간 : 3일 20시간 35분 33초", inline=False)
    embed.add_field(name=" ", value="", inline=False)
    embed.add_field(name=" ", value="임신시간 : 3시간 58분 5초", inline=False)
    embed.add_field(name=" ", value="베이비 : 9시간 15분 33초", inline=False)
    embed.add_field(name=" ", value="성장기 : 1일 13시간 2분 13초", inline=False)
    embed.add_field(name=" ", value="성숙기 : 1일 22시간 17분 46초", inline=False)
    embed.add_field(name="", value="", inline=True)
    embed.set_footer(text="Made by WELCIKS")
    await ctx.respond(embed=embed)

@client.slash_command(guild_ids = [934742265828614165], description="테리지노사우루스 성장시간")
async def 테리지노(ctx):
    embed=discord.Embed(title=" ", description="공식 오피셜 성장시간 ( x 1 )", color=0xb750fb)
    embed.set_author(name="테리지노사우루스 / Therizinosaur")
    embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/806894932836220928/806896780196446278/therizinosaurus.png')
    embed.add_field(name="", value="", inline=True)
    embed.add_field(name="  성장시간", value="", inline=False)
    embed.add_field(name="", value="총 성장시간 : 4일 19시간 44분 26초", inline=False)
    embed.add_field(name=" ", value="", inline=False)
    embed.add_field(name=" ", value="알 부화시간 : 1시간 39분 59초", inline=False)
    embed.add_field(name=" ", value="베이비 : 11시간 34분 26초", inline=False)
    embed.add_field(name=" ", value="성장기 : 1일 22시간 17분 46초", inline=False)
    embed.add_field(name=" ", value="성숙기 : 2일 9시간 52분 13초", inline=False)
    embed.add_field(name="", value="", inline=True)
    embed.set_footer(text="Made by WELCIKS")
    await ctx.respond(embed=embed)

@client.slash_command(guild_ids = [934742265828614165], description="쉐도우메인 성장시간")
async def 쉐메(ctx):
    embed=discord.Embed(title=" ", description="공식 오피셜 성장시간 ( x 1 )", color=0xb750fb)
    embed.set_author(name="쉐도우메인 / Shadowmane")
    embed.set_thumbnail(url='https://o.remove.bg/downloads/5ff38b0a-0e07-47a3-9136-a680c5ee13fc/ACTUAL-BLACK-removebg-preview-removebg-preview.png')
    embed.add_field(name="", value="", inline=True)
    embed.add_field(name="  성장시간", value="", inline=False)
    embed.add_field(name="", value="총 성장시간 : 2일 43분 58초", inline=False)
    embed.add_field(name=" ", value="", inline=False)
    embed.add_field(name=" ", value="임신시간 : 2시간 23분 48초", inline=False)
    embed.add_field(name=" ", value="베이비 : 4시간 52분 23초", inline=False)
    embed.add_field(name=" ", value="성장기 : 19시 29분 35초", inline=False)
    embed.add_field(name=" ", value="성숙기 : 1일 21분 59초", inline=False)
    embed.add_field(name="", value="", inline=True)
    embed.set_footer(text="Made by WELCIKS")
    await ctx.respond(embed=embed)

@client.slash_command(guild_ids = [934742265828614165], description="렉스 성장시간")
async def 렉스(ctx):
    embed=discord.Embed(title=" ", description="공식 오피셜 성장시간 ( x 1 )", color=0xb750fb)
    embed.set_author(name="렉스 / Rex")
    embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/806894932836220928/806896810333044836/rex.png')
    embed.add_field(name="", value="", inline=True)
    embed.add_field(name="  성장시간", value="", inline=False)
    embed.add_field(name="", value="총 성장시간 : 3일 20시간 35분 33초", inline=False)
    embed.add_field(name=" ", value="", inline=False)
    embed.add_field(name=" ", value="알 부화시간 : 4시간 59분 58초", inline=False)
    embed.add_field(name=" ", value="베이비 : 9시간 15분 33초", inline=False)
    embed.add_field(name=" ", value="성장기 : 1일 13시간 2분 13초", inline=False)
    embed.add_field(name=" ", value="성숙기 : 1일 22시간 17분 46초", inline=False)
    embed.add_field(name="", value="", inline=True)
    embed.set_footer(text="Made by WELCIKS")
    await ctx.respond(embed=embed)

@client.slash_command(guild_ids = [934742265828614165], description="사마귀 성장시간")
async def 사마귀(ctx):
    embed=discord.Embed(title=" ", description="공식 오피셜 성장시간 ( x 1 )", color=0xb750fb)
    embed.set_author(name="사마귀 / Mantis")
    embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/806894932836220928/806897004445696010/mantis.png')
    embed.add_field(name="", value="", inline=True)
    embed.add_field(name="  성장시간", value="", inline=False)
    embed.add_field(name="", value="총 성장시간 : 2일 6시간 27분 58초", inline=False)
    embed.add_field(name=" ", value="", inline=False)
    embed.add_field(name=" ", value="알 부화시간 : 2시간 46분 39초", inline=False)
    embed.add_field(name=" ", value="베이비 : 5시간 26분 47초", inline=False)
    embed.add_field(name=" ", value="성장기 : 21시간 47분 11초", inline=False)
    embed.add_field(name=" ", value="성숙기 : 1일 3시간 13분 59초", inline=False)
    embed.add_field(name="", value="", inline=True)
    embed.set_footer(text="Made by WELCIKS")
    await ctx.respond(embed=embed)

@client.slash_command(guild_ids = [934742265828614165], description="데스모두스 성장시간")
async def 데스모(ctx):
    embed=discord.Embed(title=" ", description="공식 오피셜 성장시간 ( x 1 )", color=0xb750fb)
    embed.set_author(name="데스모두스 / Desmodus")
    embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/806893887162548244/806893972525023312/onyc.png')
    embed.add_field(name="", value="", inline=True)
    embed.add_field(name="  성장시간", value="", inline=False)
    embed.add_field(name="", value="총 성장시간 : 2일 23시간 13분 30초", inline=False)
    embed.add_field(name=" ", value="", inline=False)
    embed.add_field(name=" ", value="임신시간 : 7시간 56분 11초", inline=False)
    embed.add_field(name=" ", value="베이비 : 7시간 7분 21초", inline=False)
    embed.add_field(name=" ", value="성장기 : 1일 4시간 29분 24초", inline=False)
    embed.add_field(name=" ", value="성숙기 : 1일 11시간 36분 45초", inline=False)
    embed.add_field(name="", value="", inline=True)
    embed.set_footer(text="Made by WELCIKS")
    await ctx.respond(embed=embed)

@client.slash_command(guild_ids = [934742265828614165], description="투소테우티스 성장시간")
async def 투소(ctx):
    embed=discord.Embed(title=" ", description="공식 오피셜 성장시간 ( x 1 )", color=0xb750fb)
    embed.set_author(name="투소테우티스 / Tusoteuthis")
    embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/806894251073208330/806894678011674634/tusoteuthis.png')
    embed.add_field(name="", value="", inline=True)
    embed.add_field(name="  성장시간", value="", inline=False)
    embed.add_field(name="", value="총 성장시간 : 7일 17시간 11분 6초", inline=False)
    embed.add_field(name=" ", value="", inline=False)
    embed.add_field(name=" ", value="알 부화시간 : 4시간 59분 58초", inline=False)
    embed.add_field(name=" ", value="베이비 : 18시간 31분 6초", inline=False)
    embed.add_field(name=" ", value="성장기 : 3일 2시간 4분 26초", inline=False)
    embed.add_field(name=" ", value="성숙기 : 3일 20시간 35분 33초", inline=False)
    embed.add_field(name="", value="", inline=True)
    embed.set_footer(text="Made by WELCIKS")
    await ctx.respond(embed=embed)

@client.slash_command(guild_ids = [934742265828614165], description="유티라누스 성장시간")
async def 유티(ctx):
    embed=discord.Embed(title=" ", description="공식 오피셜 성장시간 ( x 1 )", color=0xb750fb)
    embed.set_author(name="유티라누스 / Yutyrannus")
    embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/806894932836220928/806896756679508008/yutyrannus.png')
    embed.add_field(name="", value="", inline=True)
    embed.add_field(name="  성장시간", value="", inline=False)
    embed.add_field(name="", value="총 성장시간 : 7일 17시간 11분 6초", inline=False)
    embed.add_field(name=" ", value="", inline=False)
    embed.add_field(name=" ", value="알 부화시간 : 4시간 59분 58초", inline=False)
    embed.add_field(name=" ", value="베이비 : 18시간 31분 6초", inline=False)
    embed.add_field(name=" ", value="성장기 : 3일 2시간 4분 26초", inline=False)
    embed.add_field(name=" ", value="성숙기 : 3일 20시간 35분 33초", inline=False)
    embed.add_field(name="", value="", inline=True)
    embed.set_footer(text="Made by WELCIKS")
    await ctx.respond(embed=embed)

@client.slash_command(guild_ids = [934742265828614165], description="케찰 성장시간")
async def 케찰(ctx):
    embed=discord.Embed(title=" ", description="공식 오피셜 성장시간 ( x 1 )", color=0xb750fb)
    embed.set_author(name="케찰 / Quetzal")
    embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/806893887162548244/806893917949526096/quetzal-1.png')
    embed.add_field(name="", value="", inline=True)
    embed.add_field(name="  성장시간", value="", inline=False)
    embed.add_field(name="", value="총 성장시간 : 5일 12시간 16분 30초", inline=False)
    embed.add_field(name=" ", value="", inline=False)
    embed.add_field(name=" ", value="알 부화시간 : 16시간 39분 55초", inline=False)
    embed.add_field(name=" ", value="베이비 : 13시간 13분 39초", inline=False)
    embed.add_field(name=" ", value="성장기 : 2일 4시간 54분 36초", inline=False)
    embed.add_field(name=" ", value="성숙기 : 2일 18시간 8분 15초", inline=False)
    embed.add_field(name="", value="", inline=True)
    embed.set_footer(text="Made by WELCIKS")
    await ctx.respond(embed=embed)

@client.slash_command(guild_ids = [934742265828614165], description="카르보네미스 성장시간")
async def 카르보(ctx):
    embed=discord.Embed(title=" ", description="공식 오피셜 성장시간 ( x 1 )", color=0xb750fb)
    embed.set_author(name="카르보네미스 / Carbonemys")
    embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/806894932836220928/806897238429007892/carbonemys.png')
    embed.add_field(name="", value="", inline=True)
    embed.add_field(name="  성장시간", value="", inline=False)
    embed.add_field(name="", value="총 성장시간 : 23시간 8분 53초", inline=False)
    embed.add_field(name=" ", value="", inline=False)
    embed.add_field(name=" ", value="알 부화시간 : 1시간 14분 59초", inline=False)
    embed.add_field(name=" ", value="베이비 : 2시간 18분 53초", inline=False)
    embed.add_field(name=" ", value="성장기 : 9시간 15분 33초", inline=False)
    embed.add_field(name=" ", value="성숙기 : 11시간 34분 26초", inline=False)
    embed.add_field(name="", value="", inline=True)
    embed.set_footer(text="Made by WELCIKS")
    await ctx.respond(embed=embed)

@client.slash_command(guild_ids = [934742265828614165], description="카르노타우루스 성장시간")
async def 카르노(ctx):
    embed=discord.Embed(title=" ", description="공식 오피셜 성장시간 ( x 1 )", color=0xb750fb)
    embed.set_author(name="카르노타우루스 / Carnotaurus")
    embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/806894932836220928/806897237745074217/carnotaurus.png')
    embed.add_field(name="", value="", inline=True)
    embed.add_field(name="  성장시간", value="", inline=False)
    embed.add_field(name="", value="총 성장시간 : 1일 22시간 17분 46초", inline=False)
    embed.add_field(name=" ", value="", inline=False)
    embed.add_field(name=" ", value="알 부화시간 : 1시간 39분 59초", inline=False)
    embed.add_field(name=" ", value="베이비 : 4시간 37분 46초", inline=False)
    embed.add_field(name=" ", value="성장기 : 18시간 31분 6초", inline=False)
    embed.add_field(name=" ", value="성숙기 : 23시간 8분 53초", inline=False)
    embed.add_field(name="", value="", inline=True)
    embed.set_footer(text="Made by WELCIKS")
    await ctx.respond(embed=embed)

@client.slash_command(guild_ids = [934742265828614165], description="데이노니쿠스 성장시간")
async def 데이노(ctx):
    embed=discord.Embed(title=" ", description="공식 오피셜 성장시간 ( x 1 )", color=0xb750fb)
    embed.set_author(name="데이노니쿠스 / Deinonychus")
    embed.set_thumbnail(url='https://o.remove.bg/downloads/1ec9baaa-e3d6-4645-b04f-a52fb73f875c/images-removebg-preview.png')
    embed.add_field(name="", value="", inline=True)
    embed.add_field(name="  성장시간", value="", inline=False)
    embed.add_field(name="", value="총 성장시간 : 1일 13시간 2분 13초", inline=False)
    embed.add_field(name=" ", value="", inline=False)
    embed.add_field(name=" ", value="알 부화시간 : 4시간 59분 58초", inline=False)
    embed.add_field(name=" ", value="베이비 : 3시간 42분 13초", inline=False)
    embed.add_field(name=" ", value="성장기 : 14시간 48분 53초", inline=False)
    embed.add_field(name=" ", value="성숙기 : 18시간 31분 6초", inline=False)
    embed.add_field(name="", value="", inline=True)
    embed.set_footer(text="Made by WELCIKS")
    await ctx.respond(embed=embed)

@client.slash_command(guild_ids = [934742265828614165], description="블러드스토커 성장시간")
async def 블스(ctx):
    embed=discord.Embed(title=" ", description="공식 오피셜 성장시간 ( x 1 )", color=0xb750fb)
    embed.set_author(name="블러드스토커 / Bloodstalker")
    embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/806894932836220928/806897238722216006/bloodstalker.png')
    embed.add_field(name="", value="", inline=True)
    embed.add_field(name="  성장시간", value="", inline=False)
    embed.add_field(name="", value="총 성장시간 : 2일 6시간 27분 58초", inline=False)
    embed.add_field(name=" ", value="", inline=False)
    embed.add_field(name=" ", value="알 부화시간 : 2시간 56분 27초", inline=False)
    embed.add_field(name=" ", value="베이비 : 5시간 26분 47초", inline=False)
    embed.add_field(name=" ", value="성장기 : 21시간 47분 11초", inline=False)
    embed.add_field(name=" ", value="성숙기 : 1일 3시간 13분 59초", inline=False)
    embed.add_field(name="", value="", inline=True)
    embed.set_footer(text="Made by WELCIKS")
    await ctx.respond(embed=embed)

@client.slash_command(guild_ids = [934742265828614165], description="스피노 성장시간")
async def 스피노(ctx):
    embed=discord.Embed(title=" ", description="공식 오피셜 성장시간 ( x 1 )", color=0xb750fb)
    embed.set_author(name="스피노 / Spino")
    embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/806894932836220928/806896780670664724/spinosaur.png')
    embed.add_field(name="", value="", inline=True)
    embed.add_field(name="  성장시간", value="", inline=False)
    embed.add_field(name="", value="총 성장시간 : 2일 23시간 13분 30초", inline=False)
    embed.add_field(name=" ", value="", inline=False)
    embed.add_field(name=" ", value="알 부화시간 : 3시간 50분 45초", inline=False)
    embed.add_field(name=" ", value="베이비 : 7시간 7분 21초", inline=False)
    embed.add_field(name=" ", value="성장기 : 1일 4시간 29분 24초", inline=False)
    embed.add_field(name=" ", value="성숙기 : 1일 11시간 36분 45초", inline=False)
    embed.add_field(name="", value="", inline=True)
    embed.set_footer(text="Made by WELCIKS")
    await ctx.respond(embed=embed)

@client.slash_command(guild_ids = [934742265828614165], description="바리오닉스 성장시간")
async def 바리오(ctx):
    embed=discord.Embed(title=" ", description="공식 오피셜 성장시간 ( x 1 )", color=0xb750fb)
    embed.set_author(name="바리오닉스 / Baryonyx")
    embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/806894251073208330/806894585674465301/baryonyx.png')
    embed.add_field(name="", value="", inline=True)
    embed.add_field(name="  성장시간", value="", inline=False)
    embed.add_field(name="", value="총 성장시간 : 1일 22시간 17분 46초", inline=False)
    embed.add_field(name=" ", value="", inline=False)
    embed.add_field(name=" ", value="알 부화시간 : 1시간 59분 59초", inline=False)
    embed.add_field(name=" ", value="베이비 : 4시간 37분 46초", inline=False)
    embed.add_field(name=" ", value="성장기 : 18시간 31분 6초", inline=False)
    embed.add_field(name=" ", value="성숙기 : 23시간 8분 53초", inline=False)
    embed.add_field(name="", value="", inline=True)
    embed.set_footer(text="Made by WELCIKS")
    await ctx.respond(embed=embed)

@client.slash_command(guild_ids = [934742265828614165], description="오비스 성장시간")
async def 오비스(ctx):
    embed=discord.Embed(title=" ", description="공식 오피셜 성장시간 ( x 1 )", color=0xb750fb)
    embed.set_author(name="오비스 / Ovis")
    embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/806894932836220928/806896934794690590/ovis.png')
    embed.add_field(name="", value="", inline=True)
    embed.add_field(name="  성장시간", value="", inline=False)
    embed.add_field(name="", value="총 성장시간 : 2일 43분 58초", inline=False)
    embed.add_field(name=" ", value="", inline=False)
    embed.add_field(name=" ", value="임신시간 : 4시간 10분 37초", inline=False)
    embed.add_field(name=" ", value="베이비 : 4시간 52분 23초", inline=False)
    embed.add_field(name=" ", value="성장기 : 19시 29분 35초", inline=False)
    embed.add_field(name=" ", value="성숙기 : 1일 21분 59초", inline=False)
    embed.add_field(name="", value="", inline=True)
    embed.set_footer(text="Made by WELCIKS")
    await ctx.respond(embed=embed)

@client.slash_command(guild_ids = [934742265828614165], description="에쿠스(유니콘) 성장시간")
async def 에쿠스(ctx):
    embed=discord.Embed(title=" ", description="공식 오피셜 성장시간 ( x 1 )", color=0xb750fb)
    embed.set_author(name="에쿠스 / Equus(Unicorn)")
    embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/806894932836220928/806897075416858624/equus.png')
    embed.add_field(name="", value="", inline=True)
    embed.add_field(name="  성장시간", value="", inline=False)
    embed.add_field(name="", value="총 성장시간 : 1일 22시간 17분 46초", inline=False)
    embed.add_field(name=" ", value="", inline=False)
    embed.add_field(name=" ", value="임신시간 : 7시간 56분 11초", inline=False)
    embed.add_field(name=" ", value="베이비 : 4시간 37분 46초", inline=False)
    embed.add_field(name=" ", value="성장기 : 18시간 31분 6초", inline=False)
    embed.add_field(name=" ", value="성숙기 : 23시간 8분 53초", inline=False)
    embed.add_field(name="", value="", inline=True)
    embed.set_footer(text="Made by WELCIKS")
    await ctx.respond(embed=embed)

@client.slash_command(guild_ids = [934742265828614165], description="파라케라테리움 성장시간")
async def 레이서(ctx):
    embed=discord.Embed(title=" ", description="공식 오피셜 성장시간 ( x 1 )", color=0xb750fb)
    embed.set_author(name="파라케라테리움 / Paraceratherium")
    embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/806894932836220928/806896841500131349/paracer.png')
    embed.add_field(name="", value="", inline=True)
    embed.add_field(name="  성장시간", value="", inline=False)
    embed.add_field(name="", value="총 성장시간 : 3일 20시간 35분 33초", inline=False)
    embed.add_field(name=" ", value="", inline=False)
    embed.add_field(name=" ", value="임신시간 : 7시간 56분 11초", inline=False)
    embed.add_field(name=" ", value="베이비 : 9시간 15분 33초", inline=False)
    embed.add_field(name=" ", value="성장기 : 1일 13시간 2분 13초", inline=False)
    embed.add_field(name=" ", value="성숙기 : 1일 22시간 17분 46초", inline=False)
    embed.add_field(name="", value="", inline=True)
    embed.set_footer(text="Made by WELCIKS")
    await ctx.respond(embed=embed)

@client.slash_command(guild_ids = [934742265828614165], description="다에오돈 성장시간")
async def 다에오돈(ctx):
    embed=discord.Embed(title=" ", description="공식 오피셜 성장시간 ( x 1 )", color=0xb750fb)
    embed.set_author(name="다에오돈 / Daeodon")
    embed.set_thumbnail(url='https://i.pinimg.com/originals/a8/1f/f5/a81ff5b85050e8e06e606acf80bd164a.png')
    embed.add_field(name="", value="", inline=True)
    embed.add_field(name="  성장시간", value="", inline=False)
    embed.add_field(name="", value="총 성장시간 : 2일 43분 58초", inline=False)
    embed.add_field(name=" ", value="", inline=False)
    embed.add_field(name=" ", value="임신시간 : 7시간 56분 11초", inline=False)
    embed.add_field(name=" ", value="베이비 : 4시간 52분 23초", inline=False)
    embed.add_field(name=" ", value="성장기 : 19시 29분 35초", inline=False)
    embed.add_field(name=" ", value="성숙기 : 1일 21분 59초", inline=False)
    embed.add_field(name="", value="", inline=True)
    embed.set_footer(text="Made by WELCIKS")
    await ctx.respond(embed=embed)

@client.slash_command(guild_ids = [934742265828614165], description="맘모스 성장시간")
async def 맘모스(ctx):
    embed=discord.Embed(title=" ", description="공식 오피셜 성장시간 ( x 1 )", color=0xb750fb)
    embed.set_author(name="맘모스 / Mammoth")
    embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/806894932836220928/806897004927254558/mammoth.png')
    embed.add_field(name="", value="", inline=True)
    embed.add_field(name="  성장시간", value="", inline=False)
    embed.add_field(name="", value="총 성장시간 : 3일 10시간 18분 16초", inline=False)
    embed.add_field(name=" ", value="", inline=False)
    embed.add_field(name=" ", value="임신시간 : 7시간 56분 11초", inline=False)
    embed.add_field(name=" ", value="베이비 : 8시간 13분 49초", inline=False)
    embed.add_field(name=" ", value="성장기 : 1일 8시간 55분 18초", inline=False)
    embed.add_field(name=" ", value="성숙기 : 1일 17시간 9분 8초", inline=False)
    embed.add_field(name="", value="", inline=True)
    embed.set_footer(text="Made by WELCIKS")
    await ctx.respond(embed=embed)

@client.slash_command(guild_ids = [934742265828614165], description="틸라콜레오 성장시간")
async def 틸라(ctx):
    embed=discord.Embed(title=" ", description="공식 오피셜 성장시간 ( x 1 )", color=0xb750fb)
    embed.set_author(name="틸라콜레오 / Thylacoleo")
    embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/806894932836220928/806896779622088704/thylacoleo.png')
    embed.add_field(name="", value="", inline=True)
    embed.add_field(name="  성장시간", value="", inline=False)
    embed.add_field(name="", value="총 성장시간 : 2일 43분 58초", inline=False)
    embed.add_field(name=" ", value="", inline=False)
    embed.add_field(name=" ", value="임신시간 : 4시간 10분 37초", inline=False)
    embed.add_field(name=" ", value="베이비 : 4시간 52분 23초", inline=False)
    embed.add_field(name=" ", value="성장기 : 19시 29분 35초", inline=False)
    embed.add_field(name=" ", value="성숙기 : 1일 21분 59초", inline=False)
    embed.add_field(name="", value="", inline=True)
    embed.set_footer(text="Made by WELCIKS")
    await ctx.respond(embed=embed)

@client.slash_command(guild_ids = [934742265828614165], description="시노마크롭스 성장시간")
async def 시노마(ctx):
    embed=discord.Embed(title=" ", description="공식 오피셜 성장시간 ( x 1 )", color=0xb750fb)
    embed.set_author(name="시노마크롭스 / Sinomacrops")
    embed.set_thumbnail(url='https://o.remove.bg/downloads/56be9a20-929a-4b2a-be3b-6de57a998041/%EC%BA%A1%EC%B2%98-removebg-preview.png')
    embed.add_field(name="", value="", inline=True)
    embed.add_field(name="  성장시간", value="", inline=False)
    embed.add_field(name="", value="총 성장시간 : 1일 13시간 2분 13초", inline=False)
    embed.add_field(name=" ", value="", inline=False)
    embed.add_field(name=" ", value="알 부화시간 : 2시간 37분 52초", inline=False)
    embed.add_field(name=" ", value="베이비 : 3시간 42분 13초", inline=False)
    embed.add_field(name=" ", value="성장기 : 14시간 48분 53초", inline=False)
    embed.add_field(name=" ", value="성숙기 : 18시간 31분 6초", inline=False)
    embed.add_field(name="", value="", inline=True)
    embed.set_footer(text="Made by WELCIKS")
    await ctx.respond(embed=embed)

@client.slash_command(guild_ids = [934742265828614165], description="타페자라 성장시간")
async def 타페(ctx):
    embed=discord.Embed(title=" ", description="공식 오피셜 성장시간 ( x 1 )", color=0xb750fb)
    embed.set_author(name="타페자라 / Tapejara")
    embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/806893887162548244/806893917369794600/tapejara-1.png')
    embed.add_field(name="", value="", inline=True)
    embed.add_field(name="  성장시간", value="", inline=False)
    embed.add_field(name="", value="총 성장시간 : 1일 3시간 13분 59초", inline=False)
    embed.add_field(name=" ", value="", inline=False)
    embed.add_field(name=" ", value="알 부화시간 : 1시간 39분 59초", inline=False)
    embed.add_field(name=" ", value="베이비 : 5시간 26분 47초", inline=False)
    embed.add_field(name=" ", value="성장기 : 21시간 47분 11초", inline=False)
    embed.add_field(name=" ", value="성숙기 : 1일 3시간 13분 59초", inline=False)
    embed.add_field(name="", value="", inline=True)
    embed.set_footer(text="Made by WELCIKS")
    await ctx.respond(embed=embed)

@client.slash_command(guild_ids = [934742265828614165], description="아트로 성장시간")
async def 아트로(ctx):
    embed=discord.Embed(title=" ", description="공식 오피셜 성장시간 ( x 1 )", color=0xb750fb)
    embed.set_author(name="아트로 / Arthropluera")
    embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/806894932836220928/806897239854546995/arthropluera.png')
    embed.add_field(name="", value="", inline=True)
    embed.add_field(name="  성장시간", value="", inline=False)
    embed.add_field(name="", value="총 성장시간 : 2일 3시간 26분 25초", inline=False)
    embed.add_field(name=" ", value="", inline=False)
    embed.add_field(name=" ", value="알 부화시간 : 2시간 29분 59초", inline=False)
    embed.add_field(name=" ", value="베이비 : 5시간 8분 38초", inline=False)
    embed.add_field(name=" ", value="성장기 : 20시간 34분 34초", inline=False)
    embed.add_field(name=" ", value="성숙기 : 1일 1시간 43분 12초", inline=False)
    embed.add_field(name="", value="", inline=True)
    embed.set_footer(text="Made by WELCIKS")
    await ctx.respond(embed=embed)

@client.slash_command(guild_ids = [934742265828614165], description="벌브독 성장시간")
async def 벌브독(ctx):
    embed=discord.Embed(title=" ", description="공식 오피셜 성장시간 ( x 1 )", color=0xb750fb)
    embed.set_author(name="벌브독 / Bulbdog")
    embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/806894932836220928/806897237929099284/bulbdog.png')
    embed.add_field(name="", value="", inline=True)
    embed.add_field(name="  성장시간", value="", inline=False)
    embed.add_field(name="", value="총 성장시간 : 2일 43분 58초", inline=False)
    embed.add_field(name=" ", value="", inline=False)
    embed.add_field(name=" ", value="임신시간 : 4시간 10분 37초", inline=False)
    embed.add_field(name=" ", value="베이비 : 4시간 52분 23초", inline=False)
    embed.add_field(name=" ", value="성장기 : 19시 29분 35초", inline=False)
    embed.add_field(name=" ", value="성숙기 : 1일 21분 59초", inline=False)
    embed.add_field(name="", value="", inline=True)
    embed.set_footer(text="Made by WELCIKS")
    await ctx.respond(embed=embed)

@client.slash_command(guild_ids = [934742265828614165], description="메갈로사우루스 성장시간")
async def 메갈로(ctx):
    embed=discord.Embed(title=" ", description="공식 오피셜 성장시간 ( x 1 )", color=0xb750fb)
    embed.set_author(name="메갈로사우루스 / Megalosaurus")
    embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/806894932836220928/806896936728526918/megalosaurus.png')
    embed.add_field(name="", value="", inline=True)
    embed.add_field(name="  성장시간", value="", inline=False)
    embed.add_field(name="", value="총 성장시간 : 3일 20시간 35분 33초", inline=False)
    embed.add_field(name=" ", value="", inline=False)
    embed.add_field(name=" ", value="알 부화시간 : 1시간 39분 59초", inline=False)
    embed.add_field(name=" ", value="베이비 : 9시간 15분 33초", inline=False)
    embed.add_field(name=" ", value="성장기 : 1일 13시간 2분 13초", inline=False)
    embed.add_field(name=" ", value="성숙기 : 1일 22시간 17분 46초", inline=False)
    embed.add_field(name="", value="", inline=True)
    embed.set_footer(text="Made by WELCIKS")
    await ctx.respond(embed=embed)

@client.slash_command(guild_ids = [934742265828614165], description="수달 성장시간")
async def 수달(ctx):
    embed=discord.Embed(title=" ", description="공식 오피셜 성장시간 ( x 1 )", color=0xb750fb)
    embed.set_author(name="수달 / Otter")
    embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/806894932836220928/806896935223033866/otter.png')
    embed.add_field(name="", value="", inline=True)
    embed.add_field(name="  성장시간", value="", inline=False)
    embed.add_field(name="", value="총 성장시간 : 21시간 2분 37초", inline=False)
    embed.add_field(name=" ", value="", inline=False)
    embed.add_field(name=" ", value="임신시간 : 7시간 56분 11초", inline=False)
    embed.add_field(name=" ", value="베이비 : 2시간 6분 15초", inline=False)
    embed.add_field(name=" ", value="성장기 : 8시간 25분 3초", inline=False)
    embed.add_field(name=" ", value="성숙기 : 10시간 31분 18초", inline=False)
    embed.add_field(name="", value="", inline=True)
    embed.set_footer(text="Made by WELCIKS")
    await ctx.respond(embed=embed)

@client.slash_command(guild_ids = [934742265828614165], description="파키 성장시간")
async def 파키(ctx):
    embed=discord.Embed(title=" ", description="공식 오피셜 성장시간 ( x 1 )", color=0xb750fb)
    embed.set_author(name="파키 / Pachy")
    embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/806894932836220928/806896842029138000/pachy.png')
    embed.add_field(name="", value="", inline=True)
    embed.add_field(name="  성장시간", value="", inline=False)
    embed.add_field(name="", value="총 성장시간 : 1일 2시간 27분 18초", inline=False)
    embed.add_field(name=" ", value="", inline=False)
    embed.add_field(name=" ", value="알 부화시간 : 1시간 25분 42초", inline=False)
    embed.add_field(name=" ", value="베이비 : 2시간 38분 43초", inline=False)
    embed.add_field(name=" ", value="성장기 : 10시간 34분 55초", inline=False)
    embed.add_field(name=" ", value="성숙기 : 13시간 13분 39초", inline=False)
    embed.add_field(name="", value="", inline=True)
    embed.set_footer(text="Made by WELCIKS")
    await ctx.respond(embed=embed)

@client.slash_command(guild_ids = [934742265828614165], description="프로콥토돈 성장시간")
async def 캥거루(ctx):
    embed=discord.Embed(title=" ", description="공식 오피셜 성장시간 ( x 1 )", color=0xb750fb)
    embed.set_author(name="프로콥토돈 / Procoptodon")
    embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/806894932836220928/806896840200683550/procoptodon.png')
    embed.add_field(name="", value="", inline=True)
    embed.add_field(name="  성장시간", value="", inline=False)
    embed.add_field(name="", value="총 성장시간 : 1일 22시간 17분 46초", inline=False)
    embed.add_field(name=" ", value="", inline=False)
    embed.add_field(name=" ", value="임신시간 : 3시간 58분 5초", inline=False)
    embed.add_field(name=" ", value="베이비 : 4시간 37분 46초", inline=False)
    embed.add_field(name=" ", value="성장기 : 18시간 31분 6초", inline=False)
    embed.add_field(name=" ", value="성숙기 : 23시간 8분 53초", inline=False)
    embed.add_field(name="", value="", inline=True)
    embed.set_footer(text="Made by WELCIKS")
    await ctx.respond(embed=embed)

@client.slash_command(guild_ids = [934742265828614165], description="롤렛 성장시간")
async def 롤렛(ctx):
    embed=discord.Embed(title=" ", description="공식 오피셜 성장시간 ( x 1 )", color=0xb750fb)
    embed.set_author(name="롤렛 / Roll Rat")
    embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/806894932836220928/806896809355903006/rollrat.png')
    embed.add_field(name="", value="", inline=True)
    embed.add_field(name="  성장시간", value="", inline=False)
    embed.add_field(name="", value="총 성장시간 : 2일 9시간 52분 13초", inline=False)
    embed.add_field(name=" ", value="", inline=False)
    embed.add_field(name=" ", value="임신시간 : 4시간 57분 37초", inline=False)
    embed.add_field(name=" ", value="베이비 : 5시간 47분 13초", inline=False)
    embed.add_field(name=" ", value="성장기 : 23시간 8분 53초", inline=False)
    embed.add_field(name=" ", value="성숙기 : 1일 4시간 56분 6초", inline=False)
    embed.add_field(name="", value="", inline=True)
    embed.set_footer(text="Made by WELCIKS")
    await ctx.respond(embed=embed)

@client.slash_command(guild_ids = [934742265828614165], description="트리케라톱스 성장시간")
async def 트리케(ctx):
    embed=discord.Embed(title=" ", description="공식 오피셜 성장시간 ( x 1 )", color=0xb750fb)
    embed.set_author(name="트리케라톱스 / Triceratops")
    embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/806894932836220928/806896758289989652/triceratops.png')
    embed.add_field(name="", value="", inline=True)
    embed.add_field(name="  성장시간", value="", inline=False)
    embed.add_field(name="", value="총 성장시간 : 1일 22시간 17분 46초", inline=False)
    embed.add_field(name=" ", value="", inline=False)
    embed.add_field(name=" ", value="알 부화시간 : 2시간 29분 59초", inline=False)
    embed.add_field(name=" ", value="베이비 : 4시간 37분 46초", inline=False)
    embed.add_field(name=" ", value="성장기 : 18시간 31분 6초", inline=False)
    embed.add_field(name=" ", value="성숙기 : 23시간 8분 53초", inline=False)
    embed.add_field(name="", value="", inline=True)
    embed.set_footer(text="Made by WELCIKS")
    await ctx.respond(embed=embed)

@client.slash_command(guild_ids = [934742265828614165], description="울리라이노 성장시간")
async def 울리(ctx):
    embed=discord.Embed(title=" ", description="공식 오피셜 성장시간 ( x 1 )", color=0xb750fb)
    embed.set_author(name="울리라이노 / Woolly Rhino")
    embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/806894932836220928/806896756049707018/woollyrhino.png')
    embed.add_field(name="", value="", inline=True)
    embed.add_field(name="  성장시간", value="", inline=False)
    embed.add_field(name="", value="총 성장시간 : 2일 9시간 52분 13초", inline=False)
    embed.add_field(name=" ", value="", inline=False)
    embed.add_field(name=" ", value="임신시간 : 3시간 58분 5초", inline=False)
    embed.add_field(name=" ", value="베이비 : 5시간 47분 13초", inline=False)
    embed.add_field(name=" ", value="성장기 : 23시간 8분 53초", inline=False)
    embed.add_field(name=" ", value="성숙기 : 1일 4시간 56분 6초", inline=False)
    embed.add_field(name="", value="", inline=True)
    embed.set_footer(text="Made by WELCIKS")
    await ctx.respond(embed=embed)

@client.slash_command(guild_ids = [934742265828614165], description="바실로사우루스 성장시간")
async def 바실로(ctx):
    embed=discord.Embed(title=" ", description="공식 오피셜 성장시간 ( x 1 )", color=0xb750fb)
    embed.set_author(name="바실로사우루스 / Basilosaurus")
    embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/806894251073208330/806894585950765086/basilosaurus.png')
    embed.add_field(name="", value="", inline=True)
    embed.add_field(name="  성장시간", value="", inline=False)
    embed.add_field(name="", value="총 성장시간 : 4일 19시간 44분 26초", inline=False)
    embed.add_field(name=" ", value="", inline=False)
    embed.add_field(name=" ", value="임신시간 : 7시간 56분 11초", inline=False)
    embed.add_field(name=" ", value="베이비 : 11시간 34분 26초", inline=False)
    embed.add_field(name=" ", value="성장기 : 1일 22시간 17분 46초", inline=False)
    embed.add_field(name=" ", value="성숙기 : 2일 9시간 52분 13초", inline=False)
    embed.add_field(name="", value="", inline=True)
    embed.set_footer(text="Made by WELCIKS")
    await ctx.respond(embed=embed)

@client.slash_command(guild_ids = [934742265828614165], description="메갈로돈 성장시간")
async def 메갈로돈(ctx):
    embed=discord.Embed(title=" ", description="공식 오피셜 성장시간 ( x 1 )", color=0xb750fb)
    embed.set_author(name="메갈로돈 / Megalodon")
    embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/806894251073208330/806894665034891294/megalodon.png')
    embed.add_field(name="", value="", inline=True)
    embed.add_field(name="  성장시간", value="", inline=False)
    embed.add_field(name="", value="총 성장시간 : 2일 23시간 13분 30초", inline=False)
    embed.add_field(name=" ", value="", inline=False)
    embed.add_field(name=" ", value="임신시간 : 6시간 6분 18초", inline=False)
    embed.add_field(name=" ", value="베이비 : 7시간 7분 21초", inline=False)
    embed.add_field(name=" ", value="성장기 : 1일 4시간 29분 24초", inline=False)
    embed.add_field(name=" ", value="성숙기 : 1일 11시간 36분 45초", inline=False)
    embed.add_field(name="", value="", inline=True)
    embed.set_footer(text="Made by WELCIKS")
    await ctx.respond(embed=embed)

@client.slash_command(guild_ids = [934742265828614165], description="메가셀론 성장시간")
async def 메가셀론(ctx):
    embed=discord.Embed(title=" ", description="공식 오피셜 성장시간 ( x 1 )", color=0xb750fb)
    embed.set_author(name="메가셀론 / Megachelon")
    embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/806894251073208330/806894664548483103/megachelon.png')
    embed.add_field(name="", value="", inline=True)
    embed.add_field(name="  성장시간", value="", inline=False)
    embed.add_field(name="", value="총 성장시간 : 3일 20시간 35분 33초", inline=False)
    embed.add_field(name=" ", value="", inline=False)
    embed.add_field(name=" ", value="알 부화시간 : 4시간 59분 58초", inline=False)
    embed.add_field(name=" ", value="베이비 : 9시간 15분 33초", inline=False)
    embed.add_field(name=" ", value="성장기 : 1일 13시간 2분 13초", inline=False)
    embed.add_field(name=" ", value="성숙기 : 1일 22시간 17분 46초", inline=False)
    embed.add_field(name="", value="", inline=True)
    embed.set_footer(text="Made by WELCIKS")
    await ctx.respond(embed=embed)

@client.slash_command(guild_ids = [934742265828614165], description="아르젠타비스 성장시간")
async def 아르젠(ctx):
    embed=discord.Embed(title=" ", description="공식 오피셜 성장시간 ( x 1 )", color=0xb750fb)
    embed.set_author(name="아르젠타비스 / Argentavis")
    embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/806893887162548244/806894008407949342/argentavis-1.png')
    embed.add_field(name="", value="", inline=True)
    embed.add_field(name="  성장시간", value="", inline=False)
    embed.add_field(name="", value="총 성장시간 : 2일 6시간 27분 58초", inline=False)
    embed.add_field(name=" ", value="", inline=False)
    embed.add_field(name=" ", value="알 부화시간 :2시간 56분 27초", inline=False)
    embed.add_field(name=" ", value="베이비 : 5시간 26분 47초", inline=False)
    embed.add_field(name=" ", value="성장기 : 21시간 47분 11초", inline=False)
    embed.add_field(name=" ", value="성숙기 : 1일 3시간 13분 59초", inline=False)
    embed.add_field(name="", value="", inline=True)
    embed.set_footer(text="Made by WELCIKS")
    await ctx.respond(embed=embed)

client.run(token)
